"""empty message

Revision ID: 23adf967c045
Revises: 
Create Date: 2020-09-08 19:26:14.612768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23adf967c045'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.String(length=222), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###
